server:
  port: 8080

spring:
  application:
    name: bff-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/999128ab-cdb0-42d7-892c-d7e8752556f9/v2.0
          audiences: d7430172-cf9c-438e-8a3a-210f88d2d23c