server:
  port: 8083

spring:
  application:
    name: ms-pedidos360-notify

  # Conexión a RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual # Exigencia del caso: ACK/NACK explícitos
        retry:
          enabled: true
          initial-interval: 2000
          max-attempts: 3