server:
  port: 8082

spring:
  application:
    name: ms-pedidos360-catalog
  
  datasource:
    url: jdbc:oracle:thin:pedidos360/password@//localhost:1521/XEPDB1
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.OracleDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/999128ab-cdb0-42d7-892c-d7e8752556f9/v2.0
          audiences: api://d7430172-cf9c-438e-8a3a-210f88d2d23c