server:
  port: 8082

spring:
  application:
    name: ms-pedidos360-catalog

  main:
    allow-bean-definition-overriding: true
  
  datasource:
    url: jdbc:oracle:thin:@oracle-pedidos360:1521/XEPDB1
    username: pedidos360
    password: password
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-timeout: 120000
      maximum-pool-size: 5
      initialization-fail-timeout: 0
  
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.OracleDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/999128ab-cdb0-42d7-892c-d7e8752556f9/v2.0
          audiences: d7430172-cf9c-438e-8a3a-210f88d2d23c